# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD — test / build / deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          pytest -q backend/tests/unit

  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env.example to .env
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env
            echo ".env file created from .env.example"
          else
            echo "[!] .env.example not found"
            exit 1
          fi

      - name: Ensure docker is available
        run: docker version

      - name: Build docker-compose images
        run: |
          set -e
          if docker compose build --pull; then
            echo "build succesful"
          else
            echo "[!] build failed"
            docker compose logs
            exit 1
          fi


  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env.example to .env
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env
            echo ".env file created from .env.example"
          else
            echo "[!] .env.example not found!"
            exit 1
          fi

      - name: Start services
        run: |
          set -e
          echo "starting services..."
          if docker compose up -d; then
            echo "services started"
          else
            echo "[!] failed to start services"
            docker compose logs
            exit 1
          fi

      - name: Wait for app to be ready
        run: |
          set -e
          for i in {1..10}; do
            if curl --fail --silent http://localhost:8000/; then
              echo "app is up!"
              exit 0
            fi
            echo "waiting for app... ($i/10)"
            sleep 2
          done
          echo "[!] app did not start in time"
          docker compose logs
          docker compose down
          exit 1

      - name: Smoke test root endpoint
        run: |
          curl -f http://localhost:8000/ || (echo "[!] smoke test failed" && exit 1)

      - name: Stop services
        if: always()
        run: |
          docker compose down

